name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Cloning this repo
        uses: actions/checkout@v2
        with:
          path: STynth
      - name: Cloning RIOT OS
        uses: actions/checkout@v2
        with:
          repository: RIOT-OS/RIOT
          path: RIOT
      - name: Install toolchain
        run: |
          sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi gcc-multilib
      - name: compile
        run: |
          WORKSPACE=$(pwd)
          make -C ${WORKSPACE}/STynth BOARD=nucleo-f767zi
